# Generated by Django 4.1 on 2023-03-23 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='data_fotogradia',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
